apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 9000
      name: http
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 10.13.64.2
