apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: lancache-dns
  namespace: lancache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lancache-dns-deployment
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

