apiVersion: v1
kind: Service
metadata:
  name: lancache-dns-service
  namespace: lancache
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  selector:
    app: lancache-dns
  ports:
    - name: dns-port
      port: 53
      targetPort: 53
      protocol: UDP
  loadBalancerIP: 10.13.8.8
  externalTrafficPolicy: Cluster
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: lancache-dns-service-tcp
  namespace: lancache
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  selector:
    app: lancache-dns
  ports:
    - name: dns-port-tcp
      port: 53
      targetPort: 53
      protocol: TCP
  loadBalancerIP: 10.13.8.8
  externalTrafficPolicy: Cluster
  type: LoadBalancer
