kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lancache-vol
  namespace: lancache
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
      