apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-default-volume 
  annotations:
    pv.beta.kubernetes.io/gid: "590" 
    volume.beta.kubernetes.io/mount-options: "auto-invalidation=no"
spec:
  capacity:
    storage: 890Gi 
  accessModes: 
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster 
    path: gv0 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gv1 
  annotations:
    pv.beta.kubernetes.io/gid: "590" 
    volume.beta.kubernetes.io/mount-options: "auto-invalidation=no"
spec:
  capacity:
    storage: 890Gi 
  accessModes: 
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster 
    path: gv1
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
