apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - port: 80
      targetPort: 3000
      name: http
  loadBalancerIP:   
  externalTrafficPolicy: Cluster
  type: LoadBalancer
