apiVersion: v1
kind: Service
metadata:
  name: lancache-monolithic-service-3
spec:
  selector:
    app: lancache-monolithic
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  loadBalancerIP: 10.13.8.103
  externalTrafficPolicy: Cluster
  type: LoadBalancer
