apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: l2-address
  namespace: metallb-system
spec:
  addresses:
  - 10.13.8.0/24

---

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: l3-address
  namespace: metallb-system
spec:
  addresses:
  - 10.13.64.0/24

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ad
  namespace: metallb-system
spec:
  ipAddressPools:
  - l2-address
  interfaces:
  - lan0
