apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-lancache
  namespace: ingress-nginx-lancache
  labels:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache
spec:
  loadBalancerIP: 10.13.8.110
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
  selector:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache

---

apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-lancache-1
  namespace: ingress-nginx-lancache
  labels:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache
spec:
  loadBalancerIP: 10.13.8.111
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
  selector:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache

---

apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-lancache-2
  namespace: ingress-nginx-lancache
  labels:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache
spec:
  loadBalancerIP: 10.13.8.112
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
  selector:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache

---

apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-lancache-3
  namespace: ingress-nginx-lancache
  labels:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache
spec:
  loadBalancerIP: 10.13.8.113
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
  selector:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache

---

apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-lancache-4
  namespace: ingress-nginx-lancache
  labels:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache
spec:
  loadBalancerIP: 10.13.8.114
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
  selector:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-lancache-5
  namespace: ingress-nginx-lancache
  labels:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache
spec:
  loadBalancerIP: 10.13.8.115
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
  selector:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-lancache-6
  namespace: ingress-nginx-lancache
  labels:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache
spec:
  loadBalancerIP: 10.13.8.116
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
  selector:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-lancache-7
  namespace: ingress-nginx-lancache
  labels:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache
spec:
  loadBalancerIP: 10.13.8.117
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
  selector:
    app.kubernetes.io/name: ingress-nginx-lancache
    app.kubernetes.io/part-of: ingress-nginx-lancache

---
