kind: PersistentVolume
apiVersion: v1
metadata:
  name: gv0
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/cluster/gv0"