apiVersion: v1
kind: Service
metadata:
  name: lancache-monolithic-service-1
  namespace: lancache 
spec:
  selector:
    app: lancache-monolithic
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 10.13.8.5

---

apiVersion: v1
kind: Service
metadata:
  name: lancache-monolithic-service-2
  namespace: lancache 
spec:  
  selector:
    app: lancache-monolithic
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 10.13.8.2

---

apiVersion: v1
kind: Service
metadata:
  name: lancache-monolithic-service-3
  namespace: lancache 
spec:  
  selector:
    app: lancache-monolithic
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 10.13.8.3

---

apiVersion: v1
kind: Service
metadata:
  name: lancache-monolithic-service-4
  namespace: lancache 
spec:  
  selector:
    app: lancache-monolithic
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 10.13.8.4